import fs from 'fs';
import path from 'path';
import { parseCSVRows, convertRowsToPlacementTests } from '../src/utils/placementCsvImporter';

const rawPromptData = `6/25/2026 11:44:16,,Thiều Thuỳ Trang 82,0326324885,0392639023,huongcohq@gmail.com,5/11/2011,Thuỳ Trang,Thuỳ Trang,"Tổ dân phố Tân Dương 3, Thuỷ Nguyên,Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",Thpt Lý Thường Kiệt,6,Lớp 12,Chưa,Người giới thiệu,went out,pour,especially,want to,take it easy,unlikely,made,have relationship very good,put out,retire,Workshops,Tamir,green,library,museum,goods,Years,0,live,Of,Using mobile phone very much can do more harm than good,There is a number of benefit uses mobile phone,The government nees to find solutions to the problem,
6/25/2026 12:41:50,,Nguyễn Thị Bích Ngà 83,0936512909,0902292339,bichnga260509@gmail.com,5/26/2009,https://www.facebook.com/share/1DNe9wQm2w/,https://www.facebook.com/share/1DNe9wQm2w/,141A/213/Thiên Lôi/Vĩnh Niệm/Lê Chân/Hải Phòng,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",Trường THPT Trần Nguyên Hãn,6.5,đầu năm sau ạ,"đã từng học 4 năm vào năm cấp 2 ạ,em không nhớ nội dung đã học",được giới thiệu qua bạn Phạm Diễm Trang ạ,went out,drop,especially,feel like,make a rest,unprobably,made,get on very well,put out,retire,8 years ,Tamer,green button,library,educational department,products,years,50,live,governments,Use mobile phone much can do more harm than good,there is a number of benefit of use mobile phone,the government need to find solution for the problem,"For me, IELTS have many benefits. I want to study IELTS because it is a globally recognized English certificate,achieve a high score can provide me good caree opportunities in the future. Additionally,it helps me provide academic english skills. Conclusion, I believe that mastering Ielts  is the first step toward professional goals and my dreams."
6/25/2026 15:43:24,,mai vân khánh 82,0389746958,0979145296,chip29439@gmai.com,11/16/2011,https://www.facebook.com/share/1CyYMGZsYf/?mibextid=wwXIfr,https://www.facebook.com/share/1CyYMGZsYf/?mibextid=wwXIfr,"116 Phương Khê,phường Kiến An","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",trường THCS Trần Phú,7.5,Lớp 12,Em chưa,Qua facebook,went out,spill,especially,feel like,take it easy,unlikely,made,get on very well,put out,resign,,Tamer,,library,education,products,year,50,live,governments,Using a mobile phone too much can do more harm than good.,There are a number of benefits of using a mobile phone.,The government needs to find a solution to this problem.,"IELTS plays a key role in everyone's life and so does it for me. Firstly,the reason I want to study IELTS because IELTS is an important certificate that helps me reduce pressure during the high school exam.Moreover, the second reason is that when studying IELTS, I have the opportunity to improve my understanding of English.In conclusion, studying IELTS also helps me get into famous universities and be more successful in life."
6/25/2026 17:12:35,,Trần Thị Biển,096770816,096770816,onlyyou.12070@gmail.com,8/10/1990,https://www.facebook.com/chuonchuon.ot.792?mibextid=wwXIfr&rdid=yZHnjTKINYkh4Cfd&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F1BTc1khS3p%2F%3Fmibextid%3DwwXIfr,https://www.facebook.com/chuonchuon.ot.792?mibextid=wwXIfr&rdid=yZHnjTKINYkh4Cfd&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F1BTc1khS3p%2F%3Fmibextid%3DwwXIfr,"Nhà số 3, ngõ 164, đồng tử, phù liễn","CS2: 15/9 Hòa Bình, Kiến An",Em không học được lịch trên ạ,hiện tại đã đi làm,5,mình ko vội,chưa ạ,qua facebook,,,,,,,,,,,,,,,,,,,,,,,,
6/25/2026 23:17:15,,Phạm Thị Hoa 86,0343466555,03333333333333,phamhoahp2000@gmail.com,8/19/2000,https://www.facebook.com/share/176CLGzNS3/?mibextid=wwXIfr,https://www.facebook.com/share/176CLGzNS3/?mibextid=wwXIfr,"Lang Thượng, xã An Khánh, Hp","CS2: 15/9 Hòa Bình, Kiến An","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",Đhhp,6,2027,Chưa,C Thu,went out,spill,specially,want to,have a relax,improbably,made,have relationship very good,put away,retire,Workshop,Tamer,Green bottle,Library ,Department ,Stores,Year,50,Live,governments,Use the mobile phone much can do more harm than good ,There are a number of benefits use the mobile phone,Government needs to find the solution problem ,"I want to study E because the mostly current companies request our employees have basic E skill.Moreover, I also frequently working with foreign customer.I must reply to email by E.And I feel E can help me to receive more opportunity jobs."
6/26/2026 11:18:40,,Trần Ngọc Minh,0818393399,0972232468,minhtranvn2k8@gmail.com,9/24/2008,https://www.facebook.com/tran.ngocminh.376695?locale=vi_VN,https://www.facebook.com/tran.ngocminh.376695?locale=vi_VN,"19/89 Tôn Đức Thắng, An Biên, Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",Không có,7,chưa biết,,Vũ Thị Huân,went out,spill,especially,have mood to,take it easy,unprobably,made,get on very well,put down,retire,18,TAMER,GREEN BUTTON,LIBRARY,,PRODUCTS,CATEGORIES,50,LIVE,GOVERNMENTS,Use of mobile phone too much can do more harm than good.,There are a number of benefit by the use of mobile phone.,Government needs to find a solution for this problem.,"I study IELTS for several reasons. When I study in university, there will be a lot of documents and curriculums which require knowing English to study. Beside, IELTS creates oppotunities for me to take a slot in student exchange program, I will have chance to study and work abroad. Last but not least, in this era, knowing English is necessary, we can not be successful without English because of its benefits in every field, from technical field to business field."
6/27/2026 12:14:36,,Trần Mai Trang,0338799258,0987098571,maitrangtr18@gmail.com,8/13/2006,https://www.facebook.com/trang.tranmai.140,https://www.facebook.com/trang.tranmai.140,phường Phù Liễn,"CS2: 15/9 Hòa Bình, Kiến An",LỚP KIẾN AN dự kiến 27/6 khai giảng : Thứ 4 Thứ 7 từ 19h45 - 21h30  (15/9 Hòa Bình Kiến An),Đại học Hải Phòng,7,K cần gấp ạ,,cô giáo tiếng Trung ak,enjoyed,pour,especially,like,make a rest,unlikely,had,get on very well,put out,end,,Tamer ,,,200765,products,year,50,live,people,Use mobile phone too much can do more harm than good.,There is a number of benefit to use mobile phone.,The goverment need find solution of problem.,"I want to study IELTS because I love studying English since I was a child. Besides, IELTS will help me learn English better at university. I can find good job in the future.However, my English is not very good now, so I need study IELTS."
6/27/2026 18:08:42,,An Vũ Ngọc Mai 82,0352511340,0365657072,anmai2197@gmail.com,8/17/2010,https://www.facebook.com/share/18uUnjKA65/,https://www.facebook.com/share/18uUnjKA65/,1187 ngô gia tự ,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT lê quý đô n,7.5,khoảng cuối kỳ 1 lớp 12,"e đã từng đi test tại trung tâm và hc thử 1 buổi , nội dung về bài hc bao gồm vx tổng quát lại Thì HTĐ,HTTD,..,MĐQH,...cách viết câu.",THANH NGỌC,went out,spill,especially,like,have a relax,improbably,made,have relationship very good,put down,finish,MODELS,TAMER,LIBRARY,,2 HUNDREDS,PRODUCTS IN SHOPS,country,50,"Live,take a holiday",goverments,Using mobile phone is too much can do more harm good,There are a number of benefits when use mobile phone,the goverment need to find solutions to deal with problems,"Actually,I want to study IETLS because i need to study abroad,find work in the future and make new friends when i go abroad .And making new friends is one of benefits when i study  abroad"
6/27/2026 20:42:08,,Vũ Anh Đức,0352090810,0793271980,vuanhduc2010hp@gmail.com,9/8/2010,https://www.facebook.com/share/1Dui1H5x6q/,https://www.facebook.com/share/1Dui1H5x6q/,TDP.Mỹ LIệt / P.Lưu KIếm / TP.Hải Phòng,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",THPT Bạch Đằng,5.5,đầu năm lớp 12,chưa,Chị Phạm Thị Ngọc Mai giới thiệu,went out,spill,especially,feel like,make it easy,unprobably,had,have relationship very good,put out,resign,,TAMER,button,,,product,year,50,,,Use moblie phones too much can do more harm than good,there are a numbur of benefit of using mobile phone,,I want to learn IELTS because it can improve my english skills. It help improve my English exam scores in the national high school graduation examination.
6/28/2026 16:44:26,,Nguyễn Tuấn Dũng 82,0337455692,0983272568,hehwoh@gmail.com,9/19/2005,https://www.facebook.com/quan.biss.9,,"số 4/117 Thiên Lôi, Phường An Biên, Lê Chân, Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",Đại học Hàng Hải Việt Nam,6.5,"Khoảng lúc ra trường nếu được ạ, em cũng không vội lắm",Em chưa học IELTS bao giờ ạ,Em biết đến qua người quen và do em tìm hiểu nữa ạ,went out,spill,especially,have mood to,have a relax,improbably,had,have relationship very good,put away,retire,8 years old,Tamer,green button,libary,education department,products in shops,year,50,live,governments,Use mobile phone too much can do more harm than good,There is a number of benifits of using mobile phone,government need to find solution for problem,"Nowadays, science and technology are increasingly developing, more countries are investing in Viet Nam. Language is very important to communicate and to integrate with other countries. English is the most popular language to learn and IELTS is one of the most famous certificate. Therefore, I choose learning IELTS to improve myself and communicate better with foreigners. IELTS is also a certificate that helps my CV look better in the eyes employers."
6/28/2026 17:48:46,,Vũ Trần Quốc Đạt 84,0917694720,0904032148,dollardat290311@gmail.com,3/29/2011,https://www.facebook.com/share/1ESbsdSCYv/,,Phường Hồng An,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Hồng Bàng,7,2028,Em chưa ạ,Em tìm hiểu qua Facebook ạ,went out,spill,especially,feel like,take it easy,unlikely,made,get on very well,put out,resign,8,Tamer,,library,,products,year,50,live,,Use mobile phone too much can do more harm than good,There is a number of benefit to using mobile phone,The goverment needs find solutions of problem,I want to study IELTS because I want to improve my English. It will help me understand English better at school.I also want to have a good certificate for my future. I am ready to study.
6/28/2026 19:53:47,,Nguyễn Chí Bảo Khánh,0914673598,0946573398,khanhbao240@gmail.com,11/15/2010,https://www.facebook.com/share/1CYgAioYcm/,, "Phường An Biên, Lê Chân, Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",THPT Trần Nguyên Hãn,7,Lớp 12,Chưa,"Qua người giới thiệu, bạn cùng lớp tên Hoàng Gia Huy",went out,spill,especially,feel like,take it easy,unlikely,made,get on very well,put out,resign,8 years,Tamer,Green button,Library,Education department,Products,Year,50,Live,Government,The use of a mobile phone too much can do more harm than good,There is a number of benefit when you use a mobile phone,Government need to find solution to this problem,"There are several reasons that make me wants to study IELTS. The best one is the degree, I can apply for points to attend university without worrying about having to take a harsh English exam. Another noticeable benefit is the amount of knowledge I can get from studying IELTS, I can learn more about grammar and new words to use in my daily life. Overall, I think studying IELTS is a good way to help me gain better position in life."
6/28/2026 22:18:02,,tran do duc tai,0975987804,0963803306,tranductai14112011@gmail.com,11/14/2011,https://www.facebook.com/share/1QPhc2heUm/,,AN HAI,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Hồng Bàng,6.5,trước kì thi thpt quốc gia,chưa,mẹ em,went out,spill,especially,have mood to,have a relax,improbably,made,have relationship very good,put out,resign,control,tamir,,library,,base on the idea ,product,50,,resident ,Using mobile phone so much can do more harm not good,there are a number of benefit of using ,goverment need to find the solution of problem,"in one day of summer after the exam i think i must study right now for the important exam in the furture . At that time i think i must lern ilets to improve English skill , vocabulary , and communicate skill in the formal place . and i find reputable center to sudy  i and think Dương VŨ  is a very  reputable center to study for long time."
`;

const header = `Timestamp,Score,Họ tên của em,Số điện thoại của em,Số điện thoại phụ huynh ,"Địa chỉ email của em, không nên dùng của bố mẹ. Nếu chưa có em lập gmail riêng, sau này thầy còn gửi bài tập qua email.",Ngày tháng năm sinh,Link facebook (chứ không chỉ ghi tên tài khoản nhé) để Dương Vũ add em vào nhóm của lớp. Tạo tài khoản nếu em chưa có nhé.,Column 42,"Địa chỉ nhà em, ghi phường/xã, quận/huyện",Chọn cơ sở em muốn đăng ký theo học,"Chọn lịch học của lớp em có thể học. Em sẽ học theo lịch sắp xếp của trung tâm tuần 2 buổi.",Trường em đang theo học,Mục tiêu của em (Ví dụ: Overall 6.0) ,Khi nào em cần chứng chỉ IELTS?,"Em đã học IELTS bao giờ chưa, nếu có ghi lại thời gian, tóm tắt qua nội dung đã học nhé.","Em biết đến IELTS Dương Vũ qua nguồn nào? Nếu có người giới thiệu, vui lòng ghi tên người giới thiệu nhé.","1. At the weekend I _________ with some friends – we went for a curry, then had a couple of drinks.","2. Every time I wear something white, I _________ coffee or orange juice or something on it.","3.  I love all fruit, but _________ strawberries.",4. I don’t _________ going out tonight.,5. I’ve been so busy all week. I don’t want to do anything at the weekend – I’ll just stay at home and _________.,"6. It’s a good idea, but it’s _________ that the boss will agree with you.","7. Excuse me, I think you’ve _________ a mistake in our bill.",8. They never argue and they enjoy spending time together. = They _________.,9. You can’t smoke here – please _________ your cigarette.,10. I don’t like my job very much. I’m going to _________ and look for another one,"Guitar Lesson Booking Form Student's name: Emily 1. __________  ",Address: 2. _____________________ Street   ,Course fee: 3. £__________   ,First lesson: 4. __________ morning  ,Bring a 5. __________ to the first class  ,The CBI believes that cities are like 1…………......….which people can buy when they go shopping. ,Surveys take place every 2………………… ,A maximum of 3……………. cities are included in the survey. ,The CBI list is helpful for: people who are trying to decide where to 4………….. or get a job.,The CBI list is helpful for: local 5…………………… who want to make their city a better place. ,1. Use/ mobile phone/ much/  can/ do / more harm/ good.,2. There/ a number of/ benefit/ use / mobile phone.,3. government/ need/ find/ solution/ problem.,"Write a short paragraph (4 sentences) about the reasons why you want to study IELTS."\n`;

const fullCsv = header + rawPromptData;
const parsedRows = parseCSVRows(fullCsv);
const importedTests = convertRowsToPlacementTests(parsedRows);

const storagePath = path.join(process.cwd(), 'server-storage', 'placementTests.json');
let existing: any[] = [];
if (fs.existsSync(storagePath)) {
  try {
    existing = JSON.parse(fs.readFileSync(storagePath, 'utf-8'));
  } catch (e) {}
}

const map = new Map<string, any>();
existing.forEach((t) => {
  const key = `${t.candidateName}-${t.phone || t.id}`;
  map.set(key, t);
});

importedTests.forEach((t) => {
  const key = `${t.candidateName}-${t.phone || t.id}`;
  if (!map.has(key)) {
    map.set(key, { ...t, sourceType: 'form_online' });
  }
});

const merged = Array.from(map.values());
fs.writeFileSync(storagePath, JSON.stringify(merged, null, 2), 'utf-8');
console.log(`Successfully merged full CSV! Total placement tests in storage: ${merged.length}`);
