import fs from 'fs';
import path from 'path';
import { parseCSVRows, convertRowsToPlacementTests } from '../src/utils/placementCsvImporter';

const csvData = `Timestamp,Score,Họ tên của em,Số điện thoại của em,Số điện thoại phụ huynh ,"Địa chỉ email của em, không nên dùng của bố mẹ. Nếu chưa có em lập gmail riêng, sau này thầy còn gửi bài tập qua email.",Ngày tháng năm sinh,Link facebook (chứ không chỉ ghi tên tài khoản nhé) để Dương Vũ add em vào nhóm của lớp. Tạo tài khoản nếu em chưa có nhé.,Column 42,"Địa chỉ nhà em, ghi phường/xã, quận/huyện",Chọn cơ sở em muốn đăng ký theo học,"Chọn lịch học của lớp em có thể học. Em sẽ học theo lịch sắp xếp của trung tâm tuần 2 buổi. 
Ca 1 từ 18.00 -19.45, ca 2 từ 19.45 - 21.30.
1. Lớp thứ 2 + thứ 5; 
2. Lớp thứ 3 + thứ 6; 
3. Lớp thứ 4 + thứ 7
Dưới đây là lịch các lớp dự kiến khai giảng sắp tới.",Trường em đang theo học,Mục tiêu của em (Ví dụ: Overall 6.0) ,Khi nào em cần chứng chỉ IELTS?,"Em đã học IELTS bao giờ chưa, nếu có ghi lại thời gian, tóm tắt qua nội dung đã học nhé.","Em biết đến IELTS Dương Vũ qua nguồn nào? Nếu có người giới thiệu, vui lòng ghi tên người giới thiệu nhé.","1. At the weekend I _________ with some friends – we went for a curry, then had a couple of drinks.","2. Every time I wear something white, I _________ coffee or orange juice or something on it.","3.  I love all fruit, but _________ strawberries.",4. I don’t _________ going out tonight.,5. I’ve been so busy all week. I don’t want to do anything at the weekend – I’ll just stay at home and _________.,"6. It’s a good idea, but it’s _________ that the boss will agree with you.","7. Excuse me, I think you’ve _________ a mistake in our bill.",8. They never argue and they enjoy spending time together. = They _________.,9. You can’t smoke here – please _________ your cigarette.,10. I don’t like my job very much. I’m going to _________ and look for another one,"Guitar Lesson Booking Form 

Student's name: Emily 1. __________  ",Address: 2. _____________________ Street   ,Course fee: 3. £__________   ,First lesson: 4. __________ morning  ,Bring a 5. __________ to the first class  ,The CBI believes that cities are like 1…………......….which people can buy when they go shopping. ,Surveys take place every 2………………… ,A maximum of 3……………. cities are included in the survey. ,The CBI list is helpful for: people who are trying to decide where to 4………….. or get a job.,The CBI list is helpful for: local 5…………………… who want to make their city a better place. ,1. Use/ mobile phone/ much/  can/ do / more harm/ good.,2. There/ a number of/ benefit/ use / mobile phone.,3. government/ need/ find/ solution/ problem.,"Write a short paragraph (4 sentences) about the reasons why you want to study IELTS. If you are confident, you can write about the benefits of studying abroad. CHOOSE ONE TOPIC ONLY."
6/23/2026 14:21:30,,Trần Khánh Ngọc  84,0772290986,0902178641,ntrankh@gmail.com,11/30/2011,https://www.facebook.com/share/191FaXm2ER/,https://www.facebook.com/share/191FaXm2ER/,"Tòa Doji, 19 Lê Hồng Phong Hải phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THCS Quang Trung,6,Lớp 12,Chưa ,Facebook ạ,went out,spill,specially,like,have a relax,unlikely,had,have relationship very good,put out,end,Workshops,Tamer,Green bottom ,Library,2765,List,Year,Best,Live,People,Use mobile phone too much can do more harmful well,There is the number of benefit using mobile phone,The government need to find solution of problem,"First, IELTS help me to high score in university exam.Second, study IELTS help me become more influent when talking with forgeigners. And if i go to study aboard, i will have many experince to my life. Not only that, i think i will have more friends from all the coutries "
6/23/2026 15:37:01,,Phạm Phương Hoa,0904287968,0984912097,phamphuonghoa2311@gmail.com,9/23/2011,https://www.facebook.com/share/1bcGr4KtNT/,https://www.facebook.com/share/1bcGr4KtNT/,Xã Nghi Dương,"CS2: 15/9 Hòa Bình, Kiến An",Em không học được lịch trên ạ,Thpt Kiến Thụy,7,Đầu lớp 12,,,went out,let,specially,have mood to,make a rest,unprobably,made,have relationship very good,put up with,finish,Support,,,,,List,Cities,50,Take a holiday,Regional government,Use a mobile phone much can do more harm than good,There a number of benefit of use mobile phone,Government need to find solution for problem,
6/23/2026 15:45:51,,Trần Ngọc Mai,0822648466,0904385399,maingctrn17@gmail.com,10/17/2011,https://www.facebook.com/maimeoooooo,https://www.facebook.com/maimeoooooo,"880 Mã Đăng Doanh, Hưng Đạo, Hải Phòng","CS2: 15/9 Hòa Bình, Kiến An",LỚP KIẾN AN dự kiến 27/6 khai giảng : Thứ 4 Thứ 7 từ 19h45 - 21h30  (15/9 Hòa Bình Kiến An),THPT Kiến Thuỵ,7.5,khi thi đại học,em chưa,mẹ giới thiệu,went out,pour,specially,like,make a rest,improbably,had,have relationship very good,put away,finish,fifteen,tamer,backpack,,82765,car,year,50,live,governments,using mobile phone too much can do more harm than good ,there are a number of benefits of using mobile phone,the government needs to find a solution to the problem,
6/23/2026 17:09:56,,Tô Bích Huyền,0931888939,0906198807,tobichhuyen@gmail.com,4/14/2011,https://www.facebook.com/share/1NFVfi93AJ/,https://www.facebook.com/share/1NFVfi93AJ/,"Xã Đông Phương ,thôn lạng côn ,huyện kiến thụy ","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",Thpt kiến thụy,4,Tháng 8 /2028,Em chưa từng học ielts,,went out,drop,specially,like,make a rest,improbably,made,have relationship very good,put out,end,,Tamer,,,,,Year,50,Live,Governments,Use of mobile phone too much can do more harm than good,There are a number of benefits of the use mobile phone.,,
6/23/2026 22:19:05,,Đoàn Trần Ngân Phương,0936818510,0988357522,nganp4089@gmail.com,2/19/2011,Em chưa có ,Em chưa có ,An Dương,"CS2: 15/9 Hòa Bình, Kiến An","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT An Dương,7.5,cuối năm lớp 11,em đã học ielts từ đầu năm lớp 8 đến hè sang lớp 9,"Mẹ em giới thiệu đến em, tên: Trần Thị Thủy",went out,spill,especially,feel like,take it easy,unlikely,made,get on very well,put out,resign,five,Tamer,green pug,library,200675,products,year,50,live,governments,Using mobile phone too much can do more harm than good.,There are a number of benefits of using mobile phone.,The government needs to find a solution to the problem.,"The reasons why I want to study IELTS is because it serves as critical gateway to local academic and professional development. Achieving a high score allows me to demonstrate my language proficiency to international universities and global employers. Furthermore, the intensive preparation process helps me improves my communication skills and critical thinking in English. Especially, it is a practical step that opens up numerous opportunities for my future development. "
6/23/2026 22:38:29,,Nguyễn Thị Hương Linh ,0935655169,0902118638,Không có,2/26/2011,@linh.599741,@linh.599741,Phường phù liễn ,"CS2: 15/9 Hòa Bình, Kiến An",Em không học được lịch trên ạ,THPT kiến an ,6.5,Khi hết lớp 12,Chưa,Hoa hiên,went for fun,spill,especially,have mood to,have a relax,improbably,had,have relationship very good,put down,resign,Workshops,,,,,Basing,20 countries ,Product ,Live,People ,Using mobile phone too much can do more harm good.,There is a number of benefit when use mobile phone.,The government need to find out solution problem ,
6/23/2026 23:05:30,,Bùi Trần Thảo Nguyên,0397282605,0975386048,Buitranthaonguyen2605@gmail.com,5/26/2010,https://www.facebook.com/share/1RrfcVbekX/?mibextid=wwXIfr,https://www.facebook.com/share/1RrfcVbekX/?mibextid=wwXIfr,"35b/138 Thiên Lôi, Phường An Biên","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Trần Nguyên Hãn,7.5,Hè lớp 11 ạ,Em chưa từng học IELTS ạ,Bùi Vĩnh Khang,went out,spill,especially,feel like,take it easy,unprobably,made,get on very well,put out,end,eight,Tamer,green button,library,museum,,year,50,live,people,Using mobile phone too much can does more harm than good,There are a number of benefits of using mobile phone,The government need to find a solution for the problem,"There are two main reasons why I want to learn IELTS. First of all, studying IELTS is very important in my learning process, especially for the university exam, it's a proof of my English skills. Secondly, in the future, I will have more opportunities to apply for a jobs. These are my answers to the question why am I decided to study IELTS"
6/24/2026 10:53:22,,trần gia bảo,0867058683,0798580168,giabaohp1301@gmail.com,1/13/2011,https://www.facebook.com/share/1bye7o1wcZ/,https://www.facebook.com/share/1bye7o1wcZ/,phường hải an,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",lê lợi,5,chưa biêt,chưa,,went out,spill,especially,like,have a relax,improbably,made,have relationship very good,put out,finish,18,tamer,green button,library,,,year,50,live,government,using mobile phone too much can do more harm than good,there are a number of benefits of using moible phone,goverment need to find solution to problem,"I want to study IELTS because i  want to be good at English . I want to improve communicate and listen skill . To sum up,i want achieve high IELTs score to apply for a job easier"
6/24/2026 18:01:54,,Đặng Thị Thu Thuỷ,0896123132,0904966914,Sleepyash2901@gmail.com,1/29/2011,https://www.facebook.com/share/18JYQV57Vq/?mibextid=wwXIfr,https://www.facebook.com/share/18JYQV57Vq/?mibextid=wwXIfr,"Phường Lê Chân, số nhà 13/166 Nguyễn Công Trứ","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THCS Trần Phú,7.5,Trước kì thi đại học,Chưa,Qua trang facebook,went out,spill,especially,feel like,take it easy,unlikely,made,get on very well,put out,resign,8,Tamer,Green button,Library,Education department,Products,Year,50,Live,Governments,Use mobile phone too much can do more harm than good,There are a number of benefit use of mobile phone,The government need to find a solution to the problem,"I intend to learn IELTS for the following reasons. Firstly, I want to learn IELTS to gain direct admission or exemption from English exams at top universities. Secondly, I am ambitious to enhance four global communication skills. Another reason that I learn IELTS is to pursue higher education abroad and secure scholarships."
6/24/2026 20:12:17,,Bùi Anh Thái,0368362918,0357138858,kimtuyenytnq@gmail.com,5/18/2011,https://www.facebook.com/?locale=vi_VN,https://www.facebook.com/?locale=vi_VN,"Ngô Quyền ,Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Thái Phiên,8.5,lớp 12,chưa,ban bè,played,drop,mostly,like,make a rest,improbably,had,have relationship very good,put up with,finish,,tamer,,libery,education,product,,50,live,,use mobile phone much more can does more harmfull at good,there a number of benefits use mobile phone,the government need find solution problem,
6/24/2026 20:38:02,,Le Thi Linh,0868972942,0868972942,Lethilinh.hvnh23@gmail.com,2/8/1995,https://www.facebook.com/share/1BWUT3JkU3/,https://www.facebook.com/share/1BWUT3JkU3/,Xã An Hưng Hải Phòng,"CS2: 15/9 Hòa Bình, Kiến An",Em không học được lịch trên ạ,Đi làm,7,Tháng 12/2027,Chưa,Facebook vợ thầy,went out,pour,specifically,like,have a relax,unlikely,made,like themselves very much,put away,resign,5,Tamer,Green button,Library,9200785,Products,Year,50,Live,Residents,Using a mobile phone too much can do more harm than good.,There is a number of benefit in use a mobile  phone.,The government needs to find solutions for the problem,"Now I am 31 years old and I want to study IELTS because of 3 reasons. Firstly, I want to improve my English to have a high-paid salary job. Secondly, I have a daughter and I want to support her in studying English. And finally, I feel I never effort to do something, I want to gain 7.0 IELTS to  be confident in myself."
6/24/2026 21:50:08,,Vũ Anh Đức,0352090810,0793271980,vuanhduc2010@gmail.com,9/8/2010,https://www.facebook.com/share/1Dui1H5x6q/,https://www.facebook.com/share/1Dui1H5x6q/,TDP.Mỹ LIệt / P.Lưu KIếm / TP.Hải Phòng,"CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",THPT Bạch Đằng,5.5,Hè lớp 11 lên 12,Em chưa,Chị Phạm Thị Ngọc Mai giới thiệu,went out,let,especially,like,take it easy,improbably,had,like themselves very much,put out,finish,,TAMER,,four seconds,,a soft drink or a car,year,50,,,use of mobile phone much can do more harm than good,There are a number of benefits to using mobile phones., the government need to find a solution problem,
6/24/2026 23:12:52,,Nguyễn Thị Mai Phương,0352090810,09620758466,mp0347875@gmail.com,2/2/2011,https://www.facebook.com/mai.phuong.27568/?locale=vi_VN,https://www.facebook.com/mai.phuong.27568/?locale=vi_VN,Phường Trần Nhân Tông / Hải Phòng,,"Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",THCS CHU VĂN  AN ,7,tháng 9-10 năm 2028 ,chưa học bao giờ ạ,,went out,spill,specifically,like,have a relax,unlikely,made,have relationship very good,put up with,finish,,tamer,library,,museum,products,useful,,live,cities,using mobile phone too much can do more harm good,there are a number of  benefit use mobile phone,government  neef find a useful solution to problem,
6/24/2026 23:15:48,,Lê Mai Hương 81,0978069410,0979602187,leemaihuong1906@gmail.com,6/19/2010,https://www.facebook.com/lee.maihuong.2025,https://www.facebook.com/lee.maihuong.2025,"18/10/191 đường Đà Nẵng, phường Ngô Quyền","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Hải An,6.5,đầu năm 2028 ,em chưa ạ,bạn em đang học tên Ngọc Khánh,went out,let,specially,want to,have a relax,unlikely,given,relate very well,put out,retire,workshops,Tamer,,museum,town,products in shop,CBI,50,take a holiday,people,Use the mobile phone is much can do more harm good ,there is a number of benefit to use the mobile phone,The government need find solution problem,"I want study ielts because it makes me hardly, have more oppotunities in studying and working. IELTS certifcate also help me apply to university more easily"
6/24/2026 23:52:18,,Nguyễn Minh Sáng 82,s,0976266779,minhsang2010hp@gmail.com,9/14/2010,https://www.facebook.com/share/18pJmVcnMn/?mibextid=wwXIfr,https://www.facebook.com/share/18pJmVcnMn/?mibextid=wwXIfr,"4/25/67 Hoàng Quý, Lê Chân, Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 19h45 - 21h30 ( 51 TÔ HIỆU)",THPT Lê Chân,6.5,Trước tháng 12 năm 2027,Em chưa ,Chị Trần Hà Vy giới thiệu cho em,went out,spill,especially,like,have a relax,improbably,done,have relationship very good,put down,finish,,Tamia,button,libary,museum,,year,,find,culture,Use mobile phone much can do more harm good.,There is a number of benefit by use mobile phone.,Government need to find solution problem.,"I want to study IELTS because it makes me better and develop my English skills. English is very important in social and my family. If I speak English well, I can get a job and make a lot of money. That's all my reasons why I want to learn IELTS.Thank you."
6/25/2026 1:23:00,,Hồ Huyền Trân,0326296383,0386342778,hohuyentran97@gmail.com,8/29/2011,https://www.facebook.com/huyen.tran.202261?,https://www.facebook.com/huyen.tran.202261?,"11/32 Tản Viên, Thượng Lý , Hồng Bàng, Hải Phòng","CS1: 51 Tô Hiệu (tầng 4), Lê Chân, Hải Phòng","Lớp PRE mới Dự kiến 26/6/2026  khai giảng, Thứ 3, thứ 6 từ 18h - 19h45 ( 51 TÔ HIỆU)",THPT Hồng Bàng,8,hết lớp 11,em chưa từng học,em được chị gia sư giới thiệu,went out,spill,specially,like,make a rest,improbably,made,have relationship very good,put away,retire,crop,tamer,every saturday,library,200765,list,year,,"visit, live",regional goverments,"if you use mobile phone so much, you can do more harm to good",there a umber of are benefit use to mobile phone,The government need to find solution problem,
6/25/2026 10:10:18,,Vũ Gia Huy 82,0377237568,0936199795,huyv1783@gmail.com,3/18/2011,https://www.facebook.com/gia.huy.210311/,https://www.facebook.com/gia.huy.210311/,"10/B184 Lý Hồng Nhật, Hải An, Hải Phòng",,"Lớp PRE mới Dự kiến 16/7/2026  khai giảng, Thứ 4, thứ 7 từ 18h - 19h45 ( 51 TÔ HIỆU)",THCS Lê Lợi ,6.5,Trước khi thi tốt nghiệp ,Chưa học IELTS bao giờ,Có người quen giới thiệu ,went out,spill,especially,have mood to,make a rest,improbably,made,get on very well,put down,finish,an aldult,TAMER,,library,200765,products,year,50,find,governments,Use mobile phone too much can do more harm than good,There are a number of benefits of using mobile ,The government  to find solution to the problem ,"I see the benefit of studying English, so i want to study EILTS. Studying EILTS helps me improve my skills like listening, speaking, reading, writing. After studying EILTS I can communicate with foreigner fluently, have more opportunity to get good jobs,....Then we learn a language help improve brain, have more confidentions in the life."
`;

const parsedRows = parseCSVRows(csvData);
console.log(`Parsed ${parsedRows.length} rows.`);

const importedTests = convertRowsToPlacementTests(parsedRows);
console.log(`Converted into ${importedTests.length} PlacementTest objects.`);

const storagePath = path.join(process.cwd(), 'server-storage', 'placementTests.json');
let existing: any[] = [];
if (fs.existsSync(storagePath)) {
  try {
    existing = JSON.parse(fs.readFileSync(storagePath, 'utf-8'));
  } catch (e) {}
}

const map = new Map<string, any>();
existing.forEach((t) => map.set(t.id || t.code, t));
importedTests.forEach((t) => {
  const key = `${t.candidateName}-${t.phone}`;
  if (!map.has(key)) {
    map.set(key, { ...t, sourceType: 'form_online' });
  }
});

const merged = Array.from(map.values());
fs.writeFileSync(storagePath, JSON.stringify(merged, null, 2), 'utf-8');
console.log(`Successfully written ${merged.length} placement tests to server storage.`);
